services:
  pingvin-share:
    container_name: app-rtransfer
    build: .
    restart: unless-stopped
    ports:
      - 3011:3000
    environment:
      - TRUST_PROXY=false
    volumes:
      - /data/rtransfer/data:/opt/app/backend/data
      - /data/rtransfer/images:/opt/app/frontend/public/img
      - /data/config/rtransfer/config.yaml:/opt/app/config.yaml
    networks:
      - ldap_my_custom_network

networks:
  ldap_my_custom_network:
    external: true
